parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  CarlosChininin\AppBundle\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/CarlosChinininAppBundle.php'
